# Template for docker_services section in ~/.config/secrets.yaml
docker_services:
  postgres:
    postgres_password: ""
    lex_db_password: ""
  rabbitmq:
    admin_password: ""
    erlang_cookie: ""
  authelia:
    jwt_secret: ""
    session_secret: ""
    encryption_key: ""
  opensearch:
    admin_password: ""
  grafana:
    admin_password: ""
