#!/bin/bash
set -euo pipefail

# Secrets initialization for lex-docker infrastructure
# Integrates with Meridian Lex ~/.config/secrets.yaml

SECRETS_FILE="$HOME/.config/secrets.yaml"
DOCKER_SECRETS_ENV="$(dirname "$0")/../docker-secrets.env"

echo "==> Initializing Docker secrets for lex-docker"

# Check if secrets.yaml exists
if [[! -f "$SECRETS_FILE" ]]; then
    echo "ERROR: $SECRETS_FILE not found"
    exit 1
fi

# Function to generate secure random password
generate_password() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
}

# Function to check if docker_services section exists
check_docker_services_section() {
    grep -q "^docker_services:" "$SECRETS_FILE"
}

# Function to get value from secrets.yaml
get_secret() {
    local key="$1"
    yq eval ".docker_services.$key" "$SECRETS_FILE" 2>/dev/null || echo "null"
}

# Function to set value in secrets.yaml
set_secret() {
    local key="$1"
    local value="$2"

    # Create docker_services section if it doesn't exist
    if! check_docker_services_section; then
        echo "docker_services:" >> "$SECRETS_FILE"
    fi

    # Set the value using yq
    yq eval -i ".docker_services.$key = \"$value\"" "$SECRETS_FILE"
}

# Ensure yq is available
if! command -v yq &> /dev/null; then
    echo "ERROR: yq is required but not installed"
    echo "Install with: sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo chmod +x /usr/local/bin/yq"
    exit 1
fi

# Generate or read secrets
declare -A SECRETS

# PostgreSQL
SECRETS[POSTGRES_PASSWORD]=$(get_secret "postgres.postgres_password")
if [[ "${SECRETS[POSTGRES_PASSWORD]}" == "null" ]]; then
    SECRETS[POSTGRES_PASSWORD]=$(generate_password)
    set_secret "postgres.postgres_password" "${SECRETS[POSTGRES_PASSWORD]}"
fi

SECRETS[LEX_DB_PASSWORD]=$(get_secret "postgres.lex_db_password")
if [[ "${SECRETS[LEX_DB_PASSWORD]}" == "null" ]]; then
    SECRETS[LEX_DB_PASSWORD]=$(generate_password)
    set_secret "postgres.lex_db_password" "${SECRETS[LEX_DB_PASSWORD]}"
fi

# RabbitMQ
SECRETS[RABBITMQ_PASSWORD]=$(get_secret "rabbitmq.admin_password")
if [[ "${SECRETS[RABBITMQ_PASSWORD]}" == "null" ]]; then
    SECRETS[RABBITMQ_PASSWORD]=$(generate_password)
    set_secret "rabbitmq.admin_password" "${SECRETS[RABBITMQ_PASSWORD]}"
fi

SECRETS[RABBITMQ_ERLANG_COOKIE]=$(get_secret "rabbitmq.erlang_cookie")
if [[ "${SECRETS[RABBITMQ_ERLANG_COOKIE]}" == "null" ]]; then
    SECRETS[RABBITMQ_ERLANG_COOKIE]=$(generate_password)
    set_secret "rabbitmq.erlang_cookie" "${SECRETS[RABBITMQ_ERLANG_COOKIE]}"
fi

# Authelia
SECRETS[AUTHELIA_JWT_SECRET]=$(get_secret "authelia.jwt_secret")
if [[ "${SECRETS[AUTHELIA_JWT_SECRET]}" == "null" ]]; then
    SECRETS[AUTHELIA_JWT_SECRET]=$(generate_password)
    set_secret "authelia.jwt_secret" "${SECRETS[AUTHELIA_JWT_SECRET]}"
fi

SECRETS[AUTHELIA_SESSION_SECRET]=$(get_secret "authelia.session_secret")
if [[ "${SECRETS[AUTHELIA_SESSION_SECRET]}" == "null" ]]; then
    SECRETS[AUTHELIA_SESSION_SECRET]=$(generate_password)
    set_secret "authelia.session_secret" "${SECRETS[AUTHELIA_SESSION_SECRET]}"
fi

SECRETS[AUTHELIA_ENCRYPTION_KEY]=$(get_secret "authelia.encryption_key")
if [[ "${SECRETS[AUTHELIA_ENCRYPTION_KEY]}" == "null" ]]; then
    SECRETS[AUTHELIA_ENCRYPTION_KEY]=$(generate_password)
    set_secret "authelia.encryption_key" "${SECRETS[AUTHELIA_ENCRYPTION_KEY]}"
fi

# OpenSearch
SECRETS[OPENSEARCH_PASSWORD]=$(get_secret "opensearch.admin_password")
if [[ "${SECRETS[OPENSEARCH_PASSWORD]}" == "null" ]]; then
    SECRETS[OPENSEARCH_PASSWORD]=$(generate_password)
    set_secret "opensearch.admin_password" "${SECRETS[OPENSEARCH_PASSWORD]}"
fi

# Grafana
SECRETS[GRAFANA_PASSWORD]=$(get_secret "grafana.admin_password")
if [[ "${SECRETS[GRAFANA_PASSWORD]}" == "null" ]]; then
    SECRETS[GRAFANA_PASSWORD]=$(generate_password)
    set_secret "grafana.admin_password" "${SECRETS[GRAFANA_PASSWORD]}"
fi

echo "==> Secrets synchronized with $SECRETS_FILE"

# Export to docker-secrets.env
cat > "$DOCKER_SECRETS_ENV" <<EOF
# Generated by init-docker-secrets.sh - DO NOT COMMIT
# Source: ~/.config/secrets.yaml

# PostgreSQL
POSTGRES_PASSWORD=${SECRETS[POSTGRES_PASSWORD]}
LEX_DB_PASSWORD=${SECRETS[LEX_DB_PASSWORD]}

# RabbitMQ
RABBITMQ_DEFAULT_USER=admin
RABBITMQ_DEFAULT_PASS=${SECRETS[RABBITMQ_PASSWORD]}
RABBITMQ_ERLANG_COOKIE=${SECRETS[RABBITMQ_ERLANG_COOKIE]}

# Authelia
AUTHELIA_JWT_SECRET=${SECRETS[AUTHELIA_JWT_SECRET]}
AUTHELIA_SESSION_SECRET=${SECRETS[AUTHELIA_SESSION_SECRET]}
AUTHELIA_ENCRYPTION_KEY=${SECRETS[AUTHELIA_ENCRYPTION_KEY]}

# OpenSearch
OPENSEARCH_INITIAL_ADMIN_PASSWORD=${SECRETS[OPENSEARCH_PASSWORD]}

# Grafana
GF_SECURITY_ADMIN_PASSWORD=${SECRETS[GRAFANA_PASSWORD]}
EOF

chmod 600 "$DOCKER_SECRETS_ENV"
chmod 600 "$SECRETS_FILE"

echo "==> Docker secrets exported to $DOCKER_SECRETS_ENV"
echo "==> File permissions set to 600"
echo ""
echo "[OK] Secrets initialization complete"
